config/routes.rb
Rails.application.routes.draw do
  resources :books, only: [:index]

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate

  # GET /books
  # GET /books.json
  def index
    @books = Book.order(:title)
    @categories = Category.order(:name)
    if @categories.count > 3
      @categories_list = @categories.each_slice((@categories.count / 3).round).to_a
    else
      @categories_list = [@categories]
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :image_url, :average_rating, :reviews_widget, :isbn, :author, :format, :category_full, :category_id)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV['AUTH_USERNAME'] && password == ENV['AUTH_PASSWORD']
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

class Float
  def star_rating
    (self*2).round / 2.0
  end
end

app/views/books/_book.html.erb
<div class="row book-row" id="book" data-category="<%= book.category.name %>">
  <div class="column small-4 medium-2">
    <div><%= image_tag book.image_url %></div>
    <a href="#" class="button tiny add-to-order" data-isbn="<%= book.isbn %>">Add to Order</a>
  </div>
  <div class="column small-8 medium-3 book-info">
    <div><%=
      link_to_if(book.url, book.title, book.url, :target => "_blank", :class=>'title') do
        content_tag(:span, book.title, {:class=>'title'})
      end %>
    </div>
    <div class="isbn"><%= book.isbn %></div>
    <div class="author"><%= book.author %></div>
    <div class="category"><%= book.category_full %></div>
    <div class="format"><%= book.format %></div>
    <div class="rating">
      <div class="stars" data-stars="<%= book.average_rating.star_rating if book.average_rating %>">
        <%= icon('star', '', class: 'star-1') %><%= icon('star-half', '', class: 'half-1') %>
        <%= icon('star', '', class: 'star-2') %><%= icon('star-half', '', class: 'half-2') %>
        <%= icon('star', '', class: 'star-3') %><%= icon('star-half', '', class: 'half-3') %>
        <%= icon('star', '', class: 'star-4') %><%= icon('star-half', '', class: 'half-4') %>
        <%= icon('star', '', class: 'star-5') %><%= icon('star-half', '', class: 'half-5') %>
      </div>
    </div>
  </div>
  <div class="column small-12 medium-7 description">
    <div class="inner">
      <%= book.description.html_safe if book.description %>
      <div class="review">
        <textarea name="review" id="review" class="review-textarea" cols="30" rows="10">
          <%= book.reviews_widget %>
        </textarea>
        <div class="review-container"></div>
        <a href="#" class="button tiny review-load">Load Review</a>
      </div>
    </div>
    <a href="#" class="readmore">Read More</a>
  </div>
</div>

app/views/books/_categories.html.erb
<% @categories_list.each do |list| %>
  <ul class="category-list no-bullet">
    <% list.each do |item| %>
      <li>
        <a href="#" class="category-link"><%= item.name %></a>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :average_rating %><br>
    <%= f.text_field :average_rating %>
  </div>
  <div class="field">
    <%= f.label :reviews_widget %><br>
    <%= f.text_area :reviews_widget %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :category_full %><br>
    <%= f.text_field :category_full %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div id="books">:

  <div class="book-list">

    <div>
      <div ng-repeat="book in books | categoryFilter:categories | cart:!cartFilter | orderBy:sortBy" class="row book-row" data-category="{{ book.category.name }}">
        <div class="column small-4 medium-2">
          <div><img src="{{ book.image_url }}" /></div>
          <button href="#" class="button tiny add-to-order" ng-click="book.cart = !book.cart">{{ book.cart ? 'Remove from Order' : 'Add to Order' }}</button>
        </div>
        <div class="column small-8 medium-3 book-info">
          <div>
            <a href="{{ book.url }}" class="title" target="_blank">
              {{ book.title }}
            </a>
          </div>
          <div class="isbn">{{ book.isbn }}</div>
          <div class="author">{{ book.author }}</div>
          <div class="category">{{ book.category_full }}</div>
          <div class="format">{{ book.format }}</div>
          <div class="rating">
            <div class="stars" data-stars="{{ book.average_rating | averageRating | number:1 }}">
              <%= icon('star', '', class: 'star-1') %><%= icon('star-half', '', class: 'half-1') %>
              <%= icon('star', '', class: 'star-2') %><%= icon('star-half', '', class: 'half-2') %>
              <%= icon('star', '', class: 'star-3') %><%= icon('star-half', '', class: 'half-3') %>
              <%= icon('star', '', class: 'star-4') %><%= icon('star-half', '', class: 'half-4') %>
              <%= icon('star', '', class: 'star-5') %><%= icon('star-half', '', class: 'half-5') %>
            </div>
          </div>
        </div>
        <div class="column small-12 medium-7 description">
          <div class="inner">
            <div ng-bind-html="book.description"></div>
            <div class="review">
              <div class="review-container"></div>
              <a href="#" class="button tiny review-load" load-review>Load Review</a>
            </div>
          </div>
          <a href="#" class="readmore">Read More</a>
        </div>
      </div>



    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @book.image_url %>
</p>

<p>
  <strong>Average rating:</strong>
  <%= @book.average_rating %>
</p>

<p>
  <strong>Reviews widget:</strong>
  <%= @book.reviews_widget %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Format:</strong>
  <%= @book.format %>
</p>

<p>
  <strong>Category full:</strong>
  <%= @book.category_full %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html lang="en">
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>SI Book Order</title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="bookApp" ng-controller="BookListCtrl">
  <div class="fixed">
    <div class="row title-row">
      <div class="column medium-4 logo">
        <%= image_tag('si-logo.png', alt:'Smashing Ideas Book Order') %>
      </div>
      <div class="column medium-8 sort-group text-right">
        <ul class="button-group sort-group__sort" data-toggle="buttons-radio">
          <li>
            <input type="radio" id="author" name="sort" value="author" ng-model="sortBy" data-toggle="button">
            <label class="button tiny" for="author">Author</label>
          </li>
          <li>
            <input type="radio" id="category" name="sort" value="category.name" ng-model="sortBy" data-toggle="button">
            <label class="button tiny" for="category">Category</label>
          </li>
          <li>
            <input type="radio" id="title" name="sort" value="title" ng-model="sortBy" data-toggle="button">
            <label class="button tiny" for="title">Title</label>
          </li>
        </ul>

        <ul class="button-group">
          <li>
            <a href="#" class="button tiny sort category selected-{{categories | categoryCount}}" id="category-filter">Filter by Category</a>
          </li>
          <li>
            <a href="#" class="button tiny sort category-reset selected-{{categories | categoryCount}}" id="category-reset" ng-click="categoryReset()">Reset</a>
          </li>
        </ul>

        <div class="cart">
          <button href="#" class="button tiny cart{{ cartFilter ? ' active' : '' }}" data-dropdown="order-form" data-options="align:left">
            Order <span class="order-num">{{ (books | cart).length}}</span>
          </button>
        </div>
      </div>
    </div>
    <div class="row category-list hidden">
      <div class="category" data-ng-repeat="category in categories">
        <!-- record that this customer has been selected -->
        <input type="checkbox" id="{{ category.id }}" class="category__checkbox" ng-checked="category.checked" ng-model="category.checked" data-toggle="button" /> <label for="{{ category.id }}" class="category__button">{{ category.name }}</label>
      </div>
    </div>
  </div>

  <%= yield %>
  <%= javascript_include_tag 'application' %>

  <div class="order-form f-dropdown content large" id="order-form" data-dropdown-content>
    <div class="row order-header">
      <div class="column small-8">
        Book Order
      </div>
      <div class="column small-4 text-right">
        <span class="order-num">{{ (books | cart).length}}</span>/7
      </div>
    </div>
    <table class="order-list">
      <tr ng-repeat="book in books | cart">
        <td>{{ book.isbn }}</td>
        <td>{{ book.title }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.category.name }}</td>
        <td>{{ book.format }}</td>
        <td>
          <a href="#" class="add-to-order remove" ng-click="book.cart = !book.cart"><i class="fa fa-minus-square"></i></a>
        </td>
      </tr>
    </table>
    <button ng-click="cartFilter = !cartFilter" class="button small {{ cartFilter ? 'active' : '' }}">Filter by Cart</button>
    <a href="http://intranet.us.randomhouse.com/empfreeord/index.cfm" class="button small right" target="_blank">Order Form</a>
  </div>

</body>
</html>